name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag archimate:$(date +%s)
    - name: Tests the Docker image is able to run the commandline app
      run: docker run -it archimate:$(date +%s) /opt/Archi/Archi -consoleLog -console -nosplash -application com.archimatetool.commandline.app --help